### ISSUE TITLE
Issue with OVH object container names containing underscore

### ISSUE THREAD

**Issue by ankitblue** [dimer47/node-ovh-objectstorage#15]
It is noted that many OVH object container names have `underscore` in their names.
We have an issue with `exist(path)` on `_.toSlug()` reformat function.

The _.toSlug changes underscore to hyphen.

**Comment by dimer47** [comment]
Hi @ankitblue,

Thank you for you feedback.
I have fix this on v2.0.3 version. You can update now the version of package to benefit from these changes.

Regards,
@dimer47

**Comment by dimer47** [comment]
cc @Alexus2
