### ISSUE TITLE
npm is not downloading the last lib

### ISSUE THREAD

**Issue by arnaudambro** [dimer47/node-ovh-objectstorage#16]
for example the `saveData` function is not available on the lib 2.0.1 I just installed

**Comment by dimer47** [comment]
Hi @arnaudambro 

Thank you for your message.
Indeed, I had accepted Reli77k's pull request but I had not merged the Dev branch with Master.

I did it, the version 2.0.2 integrate now saveData() method.

Regards,
Dimer47
