### ISSUE TITLE
Cannot user container name with uppercase

### ISSUE THREAD

**Issue by kr3niu** [dimer47/node-ovh-objectstorage#21]
I cannot use any method in `obejcts()`
Each method check if container exists, it calls `exists(container)`. This method return that container doesn't exists, but it's not true. 
My container name contains uppercase, but method `toSlug`   replace upper case with down case.
So my URL to container name is invalid.

I suggest to remove `str = str.toLowerCase();` in 14 lines of loadsh.js.
I can prepare PR

**Comment by JordiRos** [comment]
Please do, I spent many time trying to figure out why I wasn't able  to access my CameCale containers

**Comment by JordiRos** [comment]
> I cannot use any method in `obejcts()`
> Each method check if container exists, it calls `exists(container)`. This method return that container doesn't exists, but it's not true.
> My container name contains uppercase, but method `toSlug` replace upper case with down case.
> So my URL to container name is invalid.
> 
> I suggest to remove `str = str.toLowerCase();` in 14 lines of loadsh.js.
> I can prepare PR

Please do!

**Comment by dimer47** [comment]
Hello @kr3niu & @JordiRos 

Sorry for the delay,
Thanks for your feedback, I took into account your problem, I added options in the configuration object.

Here is an example:
```
// options is optionaltrad
  options: {
    slugify : true, // true, by default 
    check_exists: true, // true, by default
  }
```

I'll let you give me your feedback and in a while I'll close the issue.

**Comment by dimer47** [comment]
I close this issue.
Hoping that the solution provided satisfies you.
