### ISSUE TITLE
401 Unauthorized sometimes

### ISSUE THREAD

**Issue by arnaudambro** [dimer47/node-ovh-objectstorage#22]
Hello,

It's strange, sometimes some of my users get a 401 Unauthorized, sometimes not...
Is there a reason why ?

**Comment by dimer47** [comment]
Hello @arnaudambro,

Can this error occur if your outgoing IP address changes or if you have been logged in for too long? Are you in one of these two cases?

P.S: I do not know exactly the OVH swift session timeout.

**Comment by dimer47** [comment]
Hi @arnaudambro,

Do you still have this problem?
No response from you, I will close this issue.

**Comment by arnaudambro** [comment]
Sorry, I don't use anymore since Strasbourg fire last year, I moved to something else... 
Let's close !

**Comment by dimer47** [comment]
Ok, I understand. 
Thank you for the answer
