### ISSUE TITLE
Have you tested it with new OVH v3 changed ?

### ISSUE THREAD

**Issue by diegothucao** [dimer47/node-ovh-objectstorage#3]
Here is some update from OVH 
 http://travaux.ovh.net/?do=details&id=42314&edit=yep

I updated follow that and use this lib, it causes issue 404 ? Could you check your side as well ?
@dimer47

**Comment by antoinedray** [comment]
Hi !

I just updated the package to support OVH v3, don’t hesitate to recontact me if you encounter any other problems.

Regards,

Antoine

On 4 Mar 2020, at 9:23 AM, Thụ CAO <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is some update from OVH
http://travaux.ovh.net/?do=details&id=42314&edit=yep

I updated follow that and use this lib, it causes issue 404 ? Could you check your side as well ?
@dimer47<https://github.com/dimer47>

**Comment by dimer47** [comment]
Hello @diegothucao, 

The package has been updated to support v3 thanks to the contribution of @st4nn and @antoinedray. 
A big thank you to both of them.
